### ISSUE TITLE
BIDS-iEEG spec todo

### ISSUE THREAD

**Issue by choldgraf** [INCF/BIDS-examples#54]
This is a succinct to-do list for the BIDS-iEEG spec to plan out what needs to happen for v1.0 to be finalized!

### Todo items

- [ ] Finish converting half of Knight Lab data into BIDS-iEEG
- [ ] Round of feedback on the specification
- [ ] Finish second half of Knight Lab data
- [ ] Make final edits / finalize the specification
- [ ] Choose intended journal for paper
- [ ] Write up a draft for a paper to send to co-authors
- [ ] Ask for input on the following sections
  - [ ] Connection with FieldTrip
  - [ ] Connection with MNE-python
  - [ ] Connection with ielvis
- [ ] Receive feedback on the paper from co-authors
- [ ] Finalize specification 1.0
- [ ] Finalize the paper draft and submit

@dorahermes let me know if I'm missing anything, and I can update this list.
